### ISSUE TITLE
New scanner or just a scanner?

### ISSUE THREAD

**Issue by Amorymeltzer** [joaquin-sch/BaseConstruction#4]
Line 62 of BaseScan.cfg (and hence the contract itself) says:

`title = Launch a new scanner into @/targetBody2 orbit`

When stock contracts say "Launch a new satellite" it means it must be a NEW, not-already-launched vessel.  I initially thought the same was true for this contract but it's not - you can complete it with already-present craft.

It should probably be tweaked - to language similar to "Have a scanner in @/targetBody2 orbit", or to actually require it being a new probe.

**Comment by joaquin-sch** [comment]
Yeah thanks for this. What do you prefer ? To actually require a new probe or to just change the title

**Comment by joaquin-sch** [comment]
So now the title is changed
